//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.28 at 12:23:34 PM GMT+05:00 
//


package conv.POJO.esd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Comment"/>
 *         &lt;element ref="{}SignedByUserName"/>
 *         &lt;element ref="{}InTheNameOfUserName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "signedByUserName",
    "inTheNameOfUserName"
})
@XmlRootElement(name = "Attributes")
public class Attributes {

    @XmlElement(name = "Comment", required = true)
    protected Comment comment;
    @XmlElement(name = "SignedByUserName", required = true)
    protected SignedByUserName signedByUserName;
    @XmlElement(name = "InTheNameOfUserName", required = true)
    protected InTheNameOfUserName inTheNameOfUserName;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the signedByUserName property.
     * 
     * @return
     *     possible object is
     *     {@link SignedByUserName }
     *     
     */
    public SignedByUserName getSignedByUserName() {
        return signedByUserName;
    }

    /**
     * Sets the value of the signedByUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignedByUserName }
     *     
     */
    public void setSignedByUserName(SignedByUserName value) {
        this.signedByUserName = value;
    }

    /**
     * Gets the value of the inTheNameOfUserName property.
     * 
     * @return
     *     possible object is
     *     {@link InTheNameOfUserName }
     *     
     */
    public InTheNameOfUserName getInTheNameOfUserName() {
        return inTheNameOfUserName;
    }

    /**
     * Sets the value of the inTheNameOfUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link InTheNameOfUserName }
     *     
     */
    public void setInTheNameOfUserName(InTheNameOfUserName value) {
        this.inTheNameOfUserName = value;
    }

}
